input_video: to_track/IMG_9496_0.0_3.0.MOV
output_video: output/output.mp4
model_path: run_new/runs/train/rtdetr_exp/weights/best.pt
archi: rt-detr

class_info:
  0:
    name: pennon_attached
    color: [255, 0, 0]
  1:
    name: pennon_detached
    color: [0, 255, 0]
  2:
    name: pennon_leech
    color: [0, 0, 255]

base_class_mapping:
  0: 0
  1: 0
  2: 2

bytetrack_params:
  track_thresh: 0.5
  track_buffer: 30
  match_thresh: 0.1

blend_pairs:
  pass