input_video: data/videos/example/2Ce-CKKCtV4_35.0_40.0.mp4
output_video: output/2Ce-CKKCtV4_35.0_40.0.mp4
model_path: runs/detect/rtdetr_00/weights/best.pt
archi: rt-detr

# BGR
class_info:
  0:
    name: pennon_attached
    color: [0, 255, 0]
  1:
    name: pennon_detached
    color: [0, 0, 255]
  2:
    name: pennon_leech
    color: [255, 0, 0]

base_class_mapping:
  0: 0
  1: 0
  2: 2

bytetrack_params:
  track_thresh: 0.5
  track_buffer: 50
  match_thresh: 0.1