input_video: data/clips/2Ce-CKKCtV4.mp4
output_video: output/2Ce-CKKCtV4.mp4
model_path: runs/detect/rtdetr_01/weights/best.pt
archi: rt-detr

# BGR
class_info:
  0:
    name: pennon_attached
    color: [0, 255, 0]
  1:
    name: pennon_detached
    color: [0, 0, 255]
  2:
    name: pennon_leech
    color: [255, 0, 0]

bytetrack_params:
  track_thresh: 0.5
  track_buffer: 50
  match_thresh: 0.1